"""empty message

Revision ID: 85c2a623a9cb
Revises: 1e73df39708d
Create Date: 2025-04-29 18:41:59.902273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c2a623a9cb'
down_revision = '1e73df39708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('return_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trash', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('return_products', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('is_trash')

    # ### end Alembic commands ###
