"""empty message

Revision ID: ddb3f328dedc
Revises: 3de6c893cf43
Create Date: 2025-04-29 17:11:40.929500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb3f328dedc'
down_revision = '3de6c893cf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catagory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['catagory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('catagory_id')

    # ### end Alembic commands ###
